config/routes.rb
Rails.application.routes.draw do

  get '/rune_index' => 'home#rune_index'

  root 'home#index'
  post '/search' => 'home#search'
  get '/masteries/:summonerID' => 'home#masteries'
  get '/runes/:summonerID' => 'home#runes'
  get '/recent/:summonerID' => 'home#recent'
  get '/queue/:summonerID' => 'home#queue'
  get '/league/:summonerID' => 'home#league'

  resources :accounts

  get '/login' => 'session#new'
  post '/login' => 'session#create' #for creating account and and logging in
  delete '/login' => 'session#destroy'  #for logging out

  get '/about' => 'about#index'

  resources :conversations do
    resources :messages
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
   belongs_to :conversation
   belongs_to :account
   validates_presence_of :body, :conversation_id, :account_id

   scope :unread, -> { where(:read => false) }

   def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
   end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @account = Account.all
    @conversations = Conversation.all

      @messages = @conversation.messages

      recipient_id = @conversation.recipient_id
      sender_id = @conversation.sender_id
      @recipient = Account.find(recipient_id)
      @sender = Account.find(sender_id)


      if @messages.size > 0
        @messages.each do |msg|
          if msg.recipient_id == current_user.id
            msg.update(:read => true)
          end
        end
      end

      if @messages.length > 20
        @over_ten = true
        @messages = @messages[-20..-1]
      end

      if params[:m]
        @over_ten = false
        @messages = @conversation.messages
      end

      @c_id = params[:conversation_id]

      @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    else
      redirect_to conversations_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :account_id, :sender_id, :recipient_id)
  end

  def destroy
    @conversation = Message.find(params[:conversations_id])
    @conversation.destroy
    redirect_to conversations_path
  end

end

app/views/messages/index.html.erb
<div class="messages_body">

<!--HEADING-->
<%if current_user.id == @recipient.id%>
  <h1 class="messages_header"><%=@sender.name%></h1>
<%else%>
  <h1 class="messages_header"><%=@recipient.name%></h1>
<%end%>


<div class="message_subbody">
  <% if @over_ten %>
   <%= link_to 'Show Previous', '?m=all' %>
  <% end %>

  <div class="ui segment">
   <% @messages.each do |message| %>

    <% if message.body %>
     <% account = Account.find(message.account_id) %>
     <div class="item">
      <div class="content">
       <div class="header"><strong><%= account.name %></strong>     <%= message.message_time %></div>
        <div class="list">
         <div class="item">
          <i class="right triangle icon"></i>
           <%= message.body %>
        </div>
      </div>
     </div>
   </div>
   <% end %>
  <% end %>
  </div>
</div>

<!-- <h1>Yo bitch show me a view</h1> -->
<!-- leaving it here because it reminds me all the hardship I've went through to get this private messaging up  -->

<%= form_for [@conversation, @message], html: {class: "ui reply form"} do |f| %>
<div class="chat_message">
 <%= f.text_area :body, placeholder: "Type Message Here", class: "form-control" %>
 <%= f.text_field :account_id, value: current_user.id, type: "hidden" %>
 <%= f.text_field :sender_id, value: current_user.id, type: "hidden" %>
 <%= f.text_field :recipient_id, value: @conversation.sender_id == current_user.id ? @conversation.recipient_id : @conversation.sender_id, type: "hidden" %>
 <%= f.submit "Send", class: "submit_chat" %>
 </div>
<% end %>

<!-- <p><%= button_to 'Delete Conversation', conversation_path(@c_id), class: 'delete_convo', method: :delete %></p> -->
<%= button_to conversation_path(@c_id), class: 'delete_convo', method: :delete do %>
  <i class="fa fa-trash-o fa-2x"></i>
<%end%>

</div>
<!-- conversation_path(@c_id) is the delete route, which then accesses def destroy in conversations controller. from there, delete the convo and give it a redirection -->
<p><%= button_to 'Back', conversations_path, class: 'back_to_conversations', method: :get %></p>