config/routes.rb
Rails.application.routes.draw do

  get '/rune_index' => 'home#rune_index'

  root 'home#index'
  post '/search' => 'home#search'
  get '/masteries/:summonerID' => 'home#masteries'
  get '/runes/:summonerID' => 'home#runes'
  get '/recent/:summonerID' => 'home#recent'
  get '/queue/:summonerID' => 'home#queue'
  get '/league/:summonerID' => 'home#league'

  resources :accounts

  get '/login' => 'session#new'
  post '/login' => 'session#create' #for creating account and and logging in
  delete '/login' => 'session#destroy'  #for logging out

  get '/about' => 'about#index'

  resources :conversations do
    resources :messages
  end

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'Account'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'Account'

  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where(
      "conversations.sender_id = ? AND
      conversations.recipient_id = ? OR
      conversations.sender_id = ? AND
      conversations.recipient_id =? ",
      sender_id, recipient_id, recipient_id, sender_id
      )
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :logged_in?

  def index
    @account = Account.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id], params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    redirect_to conversation_messages_path(@conversation)
  end

  def destroy
    @conversation = Conversation.find(params[:id])
    @conversation.destroy
    redirect_to conversations_path
  end

private

  def conversation_params
    params.permit(:sender_id, :recipient_id, :contributor_id)
  end

end

app/views/conversations/index.html.erb
<div id ="conversations">

<div class=”ui segment”>
  <h1 class="conversations_heading">Chats</h1>

  <div class="conversations_body">

  <div class=”ui list”>
    <div class=”item”>
      <% @conversations.each do |conversation| %>
        <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>

          <% if conversation.sender_id == current_user.id %>
            <% recipient = Account.find(conversation.recipient_id) %>
          <% else %>
            <% recipient = Account.find(conversation.sender_id) %>
          <% end %>

        <%= link_to recipient.name, conversation_messages_path(conversation), class: 'buddy_name'%><br>
       <% end %>
     <% end %>
   </div>
 </div>
</div>
</div>

</div>
<p><%= button_to 'Back', accounts_path(@account), class: 'back_to_chats', method: :get %></p>



</div>