config/routes.rb
Rails.application.routes.draw do

  get '/rune_index' => 'home#rune_index'

  root 'home#index'
  post '/search' => 'home#search'
  get '/masteries/:summonerID' => 'home#masteries'
  get '/runes/:summonerID' => 'home#runes'
  get '/recent/:summonerID' => 'home#recent'
  get '/queue/:summonerID' => 'home#queue'
  get '/league/:summonerID' => 'home#league'

  resources :accounts

  get '/login' => 'session#new'
  post '/login' => 'session#create' #for creating account and and logging in
  delete '/login' => 'session#destroy'  #for logging out

  get '/about' => 'about#index'

  resources :conversations do
    resources :messages
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
    has_secure_password
    validates :name, :uniqueness => true
    validates :lol_username, presence: true
    # validates :email, :uniqueness => true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

    validates_confirmation_of :password, allow_nil: true
    # validates :fav_champion, presence: true
end

app/models/champion.rb
class Champion < ActiveRecord::Base
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'Account'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'Account'

  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where(
      "conversations.sender_id = ? AND
      conversations.recipient_id = ? OR
      conversations.sender_id = ? AND
      conversations.recipient_id =? ",
      sender_id, recipient_id, recipient_id, sender_id
      )
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/map.rb
class Map < ActiveRecord::Base
end

app/models/mastery.rb
class Mastery < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
   belongs_to :conversation
   belongs_to :account
   validates_presence_of :body, :conversation_id, :account_id

   scope :unread, -> { where(:read => false) }

   def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
   end

end

app/models/rune.rb
class Rune < ActiveRecord::Base
end

app/models/spell.rb
class Spell < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @pp = Account.paginate(:page => params[:page], per_page: 10)
  end

  def create
    @account = Account.new(account_params)

    if @account.save

      session[:account_id] = @account.id  #must create a session for user to use where thet are in. database only exists while user is logged in and thats it
      redirect_to root_path  #when user creates an account, we auto log them into a 'session' and take them to the root path /homepage
    else
      redirect_to new_account_path, :flash => {:errors => @account.errors.full_messages.join(', ')}  #if user fails to create new acc, sends them back to new uesr form
    end

    # if @account.valid?
    #   redirect_to accounts_path  #redirects to accounts#index if creation is successful
    # else
    #   redirect_to new_account_path, :flash => {:errors => @account.errors.full_messages.join(', ')}  #redirects back to the form if there are errors in the sign up, does not pass validation
    # end
  end

  def new
    @account = Account.new
  end

  def edit
    @account = Account.find(params[:id])
  end

  def show
    @account = Account.find(params[:id])
    @account2 = Account.all
    @conversations = Conversation.all
  end

  def update
    @account = Account.find(params[:id])
    @account.lol_username = params[:account][:lol_username]
    @account.email = params[:account][:email]
    @account.password = params[:account][:password]
    @account.password_confirmation = params[:account][:password_confirmation]
    @account.state = params[:account][:state]
    @account.fav_champion = params[:account][:fav_champion]
    @account.fav_position = params[:account][:fav_position]
    @account.fav_gamemode = params[:account][:fav_gamemode]
    @account.fav_item = params[:account][:fav_item]
    @account.save
    # @account = Account.update(account_params)
    if @account.valid?
      redirect_to account_path  #redirects to accounts#index if creation is successful
    else
      redirect_to edit_account_path, :flash => {:errors => @account.errors.full_messages.join(', ')}  #redirects back to the form if there are errors in the sign up, does not pass validation
    end
  end

  def destroy
    @account = Account.find(params[:id])
    session[:account_id]=nil
    @account.destroy
    redirect_to root_path
  end

  def account_params
    params.required(:account).permit(:name, :lol_username, :email, :password, :password_confirmation, :state, :fav_champion, :fav_position, :fav_gamemode, :fav_item)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
  end

  def mastery_index
    @mastery_index = HTTParty.get "https://global.api.pvp.net/api/lol/static-data/oce/v1.2/mastery?masteryListData=all&api_key=f94d23f9-73a9-43e6-bf03-62156d895c2a"
  end
   
  def rune_index
    @rune_index = HTTParty.get "https://global.api.pvp.net/api/lol/static-data/oce/v1.2/rune?runeListData=all&api_key=f94d23f9-73a9-43e6-bf03-62156d895c2a"
  end

  def search
    @summoner = HTTParty.get "https://oce.api.pvp.net/api/lol/oce/v1.4/summoner/by-name/#{params[:summonerName]}?api_key=f94d23f9-73a9-43e6-bf03-62156d895c2a"
  end

  def masteries
    @masteries = HTTParty.get "https://oce.api.pvp.net/api/lol/oce/v1.4/summoner/#{params[:summonerID]}/masteries?api_key=f94d23f9-73a9-43e6-bf03-62156d895c2a"
  end

  def runes
    @runes = HTTParty.get "https://oce.api.pvp.net/api/lol/oce/v1.4/summoner/#{params[:summonerID]}/runes?api_key=f94d23f9-73a9-43e6-bf03-62156d895c2a"
  end

  def recent
    @recent = HTTParty.get "https://oce.api.pvp.net/api/lol/oce/v1.3/game/by-summoner/#{params[:summonerID]}/recent?api_key=f94d23f9-73a9-43e6-bf03-62156d895c2a"
  end

  def queue
    @queue = HTTParty.get "https://oce.api.pvp.net/api/lol/oce/v1.3/stats/by-summoner/#{params[:summonerID]}/summary?api_key=f94d23f9-73a9-43e6-bf03-62156d895c2a"
  end

  def league
    @league = HTTParty. get "https://oce.api.pvp.net/api/lol/oce/v2.5/league/by-summoner/#{params[:summonerID]}/entry?api_key=f94d23f9-73a9-43e6-bf03-62156d895c2a"
  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    account = Account.where(:name => params[:username]).first  # :username is taking the input the user puts in the login form
    if account.present?&&account.authenticate(params[:password])
      session[:account_id] = account.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:account_id] = nil
    redirect_to root_path
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mapping_helper.rb
module MappingHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper


  def notifications

    # Join the message and conversations table so you can query from both tables
    # Find me all the messages that are in conversations that I either started, or I was as recipient of.
    # Find all the unread messages and count them.

    i = 0

    my_conversations = Conversation.where('sender_id = ? OR recipient_id = ?', current_user.id, current_user.id)
    my_conversations.each do |convo|
      i = i + convo.messages.where(:recipient_id => current_user.id, :read => false).count
    end
    i

  end



end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LolProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">

  <link href='https://fonts.googleapis.com/css?family=Open+Sans|Raleway|Roboto+Slab|Merriweather|Arvo|Sigmar+One|Pacifico|Play' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Allan:bold' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lekton' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Corben:bold' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Sansita+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Covered+By+Your+Grace|Shadows+Into+Light|Architects+Daughter|Kaushan+Script|Courgette|Permanent+Marker|Rock+Salt' rel='stylesheet' type='text/css'>


</head>
<body>

  <div id="snow">

    <header class="nav">

      <ul>
        <span class="nav-left">
            <li ><%= link_to 'Home', root_path, class: 'nav_text2' %> </li>
            <li > <%= link_to 'About', about_path, class: 'nav_text2' %> </li>
            <li ><%= link_to 'Community', accounts_path, class: 'nav_text2' %></li>
        </span>

        <% if logged_in? %>
          <li><a class="welcome_user" href="/accounts/<%=current_user.id%>">Welcome, <%= current_user.name %>!</a></li>
          <li><a href="<%=conversations_path%>" class="nav_text"> Inbox (<%=notifications%>)</a> </li>  <!--the notifications here refers to the notification helper which runs the logic to spit out the counter number-->
          <li> <%= link_to 'Logout', login_path, class: 'nav_text', :method => :delete %> </li>

          <%else%>
          <li><%= link_to 'Login', login_path, class: 'nav_text' %></li>
          <li><%= link_to 'Sign Up', new_account_path, class: 'nav_text' %></li>
        <%end%>

      </ul>

    <!-- </div> -->

    </header>


<%= yield %>
  </div>

</body>
</html>